spring.application.name=scheduler

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/appointments}
spring.datasource.username=${DB_USER:appt}
spring.datasource.password=${DB_PASSWORD:appt}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:seed.sql